export const companies = [
  "ABB – Asea Brown Boveri Ltd.",
  "APC – American Power Conversion",
  "Aqualing Kft.",
  "Audi",
  "Bertelsmann Verlag",
  "Biofilter Kft.",
  "Bugnatese Hungary Kft.",
  "CAIB – Bank",
  "Consensus",
  "Creditanstalt",
  "Daimler AG Deutschland",
  "E.ON Energie",
  "Erste Bank",
  "GBMT – Rechtsanwaltskanzlei",
  "GlaxoSmithKline",
  "Guinness",
  "HiPP – Babyspeisen",
  "Hungarocamion – Logistik",
  "Inter-Európa Bank",
  "Junkers",
  "L’Oréal Paris",
  "M+W Zander",
  "MAN Kft.",
  "McCann-Erickson",
  "MHM Computer",
  "Miele Kft.",
  "Netcom Ltd. Vanuatu",
  "PubliciTeam",
  "Rhone Vet – Merial",
  "Sakret Hungária Bt.",
  "Schiesser",
  "Sopro Hungária Kft.",
  "Sto Építőanyag Kft.",
  "Vertical Flow Denmark",
  "Victus Hungária Kft.",
  "Volán Tefu – Logistik",
  "Volvo Cars Europe Trading Ltd.",
  "Volvo Trucks",
  "VW",
  "Westdeutsche Landesbank",
];

export const institutions = [
  "Dunaharaszti Városi Könyvtár",
  "MTV – Magyar Televízió",
  "Szilágyi Erzsébet Gimnázium",
  "Radnóti Miklós Színház",
  "Piros Orr Bohócdoktorok Alapítvány",
  "USF – University of San Francisco",
  "VASANOC – National Olympic Committee of Vanuatu",
];

/** Short brand names for the marquee on the home page. */
export const partnerMarquee = [
  ["Audi", "Daimler", "Volvo Cars", "VW", "Erste Bank", "L’Oréal Paris", "GlaxoSmithKline", "Guinness", "HiPP", "Miele", "Bertelsmann"],
  ["ABB", "E.ON", "Junkers", "McCann-Erickson", "MAN", "Schiesser", "Sto", "Sopro", "Creditanstalt", "Westdeutsche Landesbank", "MTV"],
];
